name: Go Integration Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Ensure go mod tidy has zero output
        run: go mod tidy -v && git diff --exit-code

      - name: Ensure gofumpt has zero output
        run: |
          go install mvdan.cc/gofumpt@latest 
          gofumpt -l -w .
          git diff --exit-code

      - name: Golang Lint
        uses: golangci/golangci-lint-action@v3
        with: 
          version: latest
          skip-pkg-cache: true
          args: --issues-exit-code=0          
          
      - name: Build project
        run: go build ./...

      - name: Run integration tests
        run: go test -v ./tests/...